name: fishroom
description: "Fishroom is an app for aquarium hobbyists to keep track of their
  fish and tanks."
publish_to: "none"
version: 0.0.7

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  crop_your_image: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  gradient_borders: ^1.0.1
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  lottie: ^3.1.2
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  skeletonizer: ^1.4.2
  supabase_flutter: ^2.6.0
  toastification: ^2.3.0
  uuid: ^4.5.0
  http:

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - .env

  fonts:
    - family: CheesyCats
      fonts:
        - asset: assets/fonts/CheesyCats.otf
