name: fishroom
description: "Fishroom is an app for aquarium hobbyists to keep track of their
  fish and tanks."
publish_to: "none"
version: 5.3.0+99

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  modal_bottom_sheet: ^3.0.0
  sprung: ^3.0.1
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  crop_your_image: ^2.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.4.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  google_sign_in: ^6.3.0
  gradient_borders: ^1.0.1
  http: null
  hydrated_bloc: ^10.1.1
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.3
  intl: ^0.20.2
  list_wheel_scroll_view_nls: ^0.0.3
  lottie: ^3.3.1
  material_symbols_icons: ^4.2815.1
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  rive: ^0.13.20
  sentry_flutter: ^9.5.0
  simple_shadow: ^0.3.1
  skeletonizer: ^2.1.0+1
  supabase_auth_ui: ^0.5.5
  supabase_flutter: ^2.9.1
  svg_flutter: ^0.0.1
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  in_app_purchase_android: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: CheesyCats
      fonts:
        - asset: assets/fonts/CheesyCats.otf
    - family: FishIcon
      fonts:
        - asset: assets/fonts/FishIcon.ttf
