name: fishroom
description: "Fishroom is an app for aquarium hobbyists to keep track of their fish and tanks."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  crop_your_image: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  package_info_plus: ^8.0.0
  supabase_flutter: ^2.5.5
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: CheesyCats
      fonts:
        - asset: assets/fonts/CheesyCats.otf
